GET http://localhost:8080/foo
Accept: text/plain

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET http://localhost:8080/foo
Accept: text/plain

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 429, "Response status is not 200");
    });
%}

###


GET http://localhost:8080/bar
Accept: text/plain

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET http://localhost:8080/foo
Accept: text/plain

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 429, "Response status is not 200");
    });
%}

###


GET http://localhost:8080/bar
Accept: text/plain

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###